version: '3.4'

networks:
  backend:
  db:

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
    - backend
    - db
  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27100:271017'
    volumes:
      - ./data/dev/mongo:/data/db
    networks:
    - db
